// Next imports
import Head from "next/head";

// React imports
import { useState } from "react";

// Components
import Header from "@/components/Header";

// Styles
import styles from "@/styles/Capacitacion.module.css";

const contents = [
	{
		id: 1,
		name: "Cuya drag",
		videoSrc: "cuyadrag.mp4",
		notas:
			"La historia de Emilia la cuya drag, una joven promesa del padel amante del padel que va por la vida comiendo aniamles exóticos.\n\nAmericanista vapeadora podría ser una de sus descripciones pero la que más le gusta es la Cuya Drag.",
	},
	{
		id: 2,
		name: "IrisAna",
		videoSrc: "hondu.mp4",
		notas:
			"Lorem 2 ipsum es el texto que se usa habitualmente en diseño gráfico en demostraciones de tipografías o de borradores de diseño para probar el diseño visual antes de insertar el texto final.",
	},
	{
		id: 3,
		name: "Pedrazon",
		videoSrc: "raya.mp4",
		notas:
			"Lorem 3 ipsum es el texto que se usa habitualmente en diseño gráfico en demostraciones de tipografías o de borradores de diseño para probar el diseño visual antes de insertar el texto final.",
	},
];

const Capacitacion = () => {
	// State to track the active tab
	const [activeTab, setActiveTab] = useState(contents[0].name);
	const [selectedCourse, setSelectedCourse] = useState(contents[0]);

	// Function to handle tab click
	const handleTabClick = (content) => {
		setSelectedCourse(content);
		setActiveTab(content.name);
	};

	return (
		<>
			<Head>
				<title>Cáritas de Monterrey | Capacitación </title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>
			<Header />
			<main>
				<section>
					<div className={styles["course-layout"]}>
						<div className={styles.sidebar}>
							{contents.map((content) => (
								<div
									key={content.id}
									className={`${styles.tab} ${
										activeTab === content.name ? styles.active : ""
									}`}
									onClick={() => handleTabClick(content)}
								>
									{content.name}
								</div>
							))}
						</div>
						<div className={styles.content}>
							<div className={styles["video-player"]}>
								<video
									key={selectedCourse.name}
									className={styles.videoControl}
									controls
								>
									<source
										src={`/videos/${selectedCourse.videoSrc}`}
										type="video/mp4"
									/>
									Your browser does not support the video tag.
								</video>
							</div>
							<div className={styles.notes}>
								<h2>Notas adicionales</h2>
								<p>{selectedCourse.notas}</p>
							</div>
						</div>
					</div>
				</section>
			</main>
		</>
	);
};

export default Capacitacion;
