// Next imports
import Head from "next/head";

// Components
import Header from "@/components/Header";

const Registro = () => {
	return (
		<>
			<Head>
				<title>Cáritas de Monterrey</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>
			<Header />
			<main>
				<section>
					<h1>Cursos registro</h1>
				</section>
			</main>
		</>
	);
};

export default Registro;
